# Generated by Django 5.1.3 on 2024-12-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T4tiffin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='contact',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
