# Generated by Django 5.1.3 on 2024-12-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('T4tiffin', '0002_studentregistration_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='school',
            new_name='school_id',
        ),
    ]
