# Generated by Django 5.1.3 on 2024-12-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('T4tiffin', '0003_rename_school_studentregistration_school_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='school_id',
            new_name='school',
        ),
    ]
