# Generated by Django 5.1.3 on 2024-12-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('T4tiffin', '0005_alter_studentregistration_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='school',
        ),
    ]
