# Generated by Django 5.1.3 on 2024-12-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('T4tiffin', '0006_remove_studentregistration_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_id',
        ),
    ]
