# Generated by Django 5.1.3 on 2024-12-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T4tiffin', '0007_remove_school_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='school_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
