# Generated by Django 5.1.3 on 2024-12-24 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T4tiffin', '0008_school_school_id_studentregistration_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='T4tiffin.school'),
        ),
    ]
